Hinet.Web/Areas/OrderInfoArea/Controllers/OrderInfoController.cs
using AutoMapper;
using CommonHelper.Excel;
using Nami.Model.Entities;
using Nami.Service.Common;
using Nami.Service.DM_DulieuDanhmucService;
using Nami.Service.OrderInfoService;
using Nami.Service.OrderInfoService.Dto;
using Nami.Web.Areas.OrderInfoArea.Models;
using Nami.Web.Filters;
using log4net;
using System;
using System.Collections.Generic;
using System.Web;
using System.Web.Mvc;
using Nami.Service.Constant;
using Nami.Service.GiaiTrinhPhanAnhService;
using Nami.Service.GiaiTrinhPhanAnhFileAttackService;
using CommonHelper.Upload;
using System.IO;
using System.Threading.Tasks;
using System.Web.Hosting;
using Nami.Web.Core;
using Nami.Service.NotificationService;

namespace Nami.Web.Areas.OrderInfoArea.Controllers
{
    public class OrderInfoController : BaseController
    {
        private readonly ILog _Ilog;
        private readonly IMapper _mapper;
        public const string permissionIndex = "OrderInfo_index";
        public const string permissionCreate = "OrderInfo_create";
        public const string permissionEdit = "OrderInfo_edit";
        public const string permissionDelete = "OrderInfo_delete";
        public const string permissionImport = "OrderInfo_Inport";
        public const string permissionExport = "OrderInfo_export";
        public const string searchKey = "OrderInfoPageSearchModel";
        private readonly IOrderInfoService _OrderInfoService;
        private readonly IDM_DulieuDanhmucService _dM_DulieuDanhmucService;
        private readonly IGiaiTrinhPhanAnhService _giaiTrinhPhanAnhService;
        private readonly IGiaiTrinhPhanAnhFileAttackService _GiaiTrinhPhanAnhFileAttackService;
        private readonly INotificationService _NotificationService;


        public OrderInfoController(IOrderInfoService OrderInfoService, ILog Ilog,

        IDM_DulieuDanhmucService dM_DulieuDanhmucService,
            IGiaiTrinhPhanAnhService giaiTrinhPhanAnhService,
            IGiaiTrinhPhanAnhFileAttackService GiaiTrinhPhanAnhFileAttackService,
            INotificationService NotificationService,
            IMapper mapper
            )
        {
            _OrderInfoService = OrderInfoService;
            _giaiTrinhPhanAnhService = giaiTrinhPhanAnhService;
            _Ilog = Ilog;
            _mapper = mapper;
            _dM_DulieuDanhmucService = dM_DulieuDanhmucService;
            _GiaiTrinhPhanAnhFileAttackService = GiaiTrinhPhanAnhFileAttackService;
            _NotificationService = NotificationService;

            var droplistMaNganHang = _dM_DulieuDanhmucService.GetDropDownListByCodeGroup(DanhMucConstant.MANGANHANG);
            SessionManager.SetValue("droplistMaNganHang", droplistMaNganHang);
            var droplistOrderType = ConstantExtension.GetDropdownData<OrderTypeConstant>(null);
            SessionManager.SetValue("droplistOrderType", droplistOrderType);

        }
        // GET: OrderInfoArea/OrderInfo
        //[PermissionAccess(Code = permissionIndex)]
        public ActionResult Index()
        {
            var PermissionWatchAll = HasPermission(PermissionCodeConst.Super_Admin);
            var listData = _OrderInfoService.GetDaTaByPageByCurrentUserIdOrAdmin(PermissionWatchAll, CurrentUserId, null);
            SessionManager.SetValue(searchKey, null);
            return View(listData);
        }

        [HttpPost]
        public JsonResult getData(int indexPage, string sortQuery, int pageSize)
        {
            var searchModel = SessionManager.GetValue(searchKey) as OrderInfoSearchDto;
            if (!string.IsNullOrEmpty(sortQuery))
            {
                if (searchModel == null)
                {
                    searchModel = new OrderInfoSearchDto();
                }
                searchModel.sortQuery = sortQuery;
                if (pageSize > 0)
                {
                    searchModel.pageSize = pageSize;
                }
                SessionManager.SetValue(searchKey, searchModel);
            }
            var PermissionWatchAll = HasPermission(PermissionCodeConst.Super_Admin);
            var data = _OrderInfoService.GetDaTaByPageByCurrentUserIdOrAdmin(PermissionWatchAll, CurrentUserId, searchModel, indexPage, pageSize);
            return Json(data);
        }
        public PartialViewResult Create()
        {
            var myModel = new CreateVM();

            return PartialView("_CreatePartial", myModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public JsonResult Create(CreateVM model)
        {
            var result = new JsonResultBO(true, "Tạo Quản lý thông tin giao dịch thành công");
            try
            {
                if (ModelState.IsValid)
                {
                    var EntityModel = _mapper.Map<OrderInfo>(model);
                    _OrderInfoService.Create(EntityModel);

                }

            }
            catch (Exception ex)
            {
                result.MessageFail(ex.Message);
                _Ilog.Error("Lỗi tạo mới Quản lý thông tin giao dịch", ex);
            }
            return Json(result);
        }

        public PartialViewResult Edit(long id)
        {
            var myModel = new EditVM();

            var obj = _OrderInfoService.GetById(id);
            if (obj == null)
            {
                throw new HttpException(404, "Không tìm thấy thông tin");
            }

            myModel = _mapper.Map(obj, myModel);
            return PartialView("_EditPartial", myModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]

        public JsonResult Edit(EditVM model)
        {
            var result = new JsonResultBO(true);
            try
            {
                if (ModelState.IsValid)
                {

                    var obj = _OrderInfoService.GetById(model.Id);
                    if (obj == null)
                    {
                        throw new Exception("Không tìm thấy thông tin");
                    }

                    obj = _mapper.Map(model, obj);
                    _OrderInfoService.Update(obj);

                }
            }
            catch (Exception ex)
            {
                result.Status = false;
                result.Message = "Không cập nhật được";
                _Ilog.Error("Lỗi cập nhật thông tin Quản lý thông tin giao dịch", ex);
            }
            return Json(result);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult searchData(OrderInfoSearchDto form)
        {
            var searchModel = SessionManager.GetValue(searchKey) as OrderInfoSearchDto;

            if (searchModel == null)
            {
                searchModel = new OrderInfoSearchDto();
                searchModel.pageSize = 20;
            }
            searchModel.IdFilterFrom = form.IdFilterFrom;
            searchModel.IdFilterTo = form.IdFilterTo;
            searchModel.AmountFilterFrom = form.AmountFilterFrom;
            searchModel.AmountFilterTo = form.AmountFilterTo;
            searchModel.OrderDescriptionFilter = form.OrderDescriptionFilter;
            searchModel.BankCodeFilter = form.BankCodeFilter;
            searchModel.OrderTypeFilter = form.OrderTypeFilter;
            searchModel.ItemTypeFilter = form.ItemTypeFilter;
            searchModel.TrangThaiThanhToanFilter = form.TrangThaiThanhToanFilter;

            SessionManager.SetValue((searchKey), searchModel);

            var PermissionWatchAll = HasPermission(PermissionCodeConst.Super_Admin);
            var data = _OrderInfoService.GetDaTaByPageByCurrentUserIdOrAdmin(PermissionWatchAll, CurrentUserId, searchModel, 1, searchModel.pageSize);
            return Json(data);
        }

        [HttpPost]
        public JsonResult Delete(long id)
        {
            var result = new JsonResultBO(true, "Xóa Quản lý thông tin giao dịch thành công");
            try
            {
                var user = _OrderInfoService.GetById(id);
                if (user == null)
                {
                    throw new Exception("Không tìm thấy thông tin để xóa");
                }
                _OrderInfoService.Delete(user);
            }
            catch (Exception ex)
            {
                result.MessageFail("Không thực hiện được");
                _Ilog.Error("Lỗi khi xóa tài khoản id=" + id, ex);
            }
            return Json(result);
        }


        public ActionResult Detail(long id)
        {
            var model = new DetailVM();
            model.objInfo = _OrderInfoService.GetDtoById(id);
            model.objGiaiTrinh = _giaiTrinhPhanAnhService.GetListGiaTrinhByPhanAnhIdAndPhanAnhType(id, ItemTypeConstant.Order);
            return View(model);
        }
        //[PermissionAccess(Code = permissionImport)]
        public FileResult ExportExcel()
        {
            var searchModel = SessionManager.GetValue(searchKey) as OrderInfoSearchDto;
            var data = _OrderInfoService.GetDaTaByPage(searchModel).ListItem;
            var dataExport = _mapper.Map<List<OrderInfoExportDto>>(data);
            var fileExcel = ExportExcelV2Helper.Export<OrderInfoExportDto>(dataExport);
            return File(fileExcel, "application/octet-stream", "OrderInfo.xlsx");
        }

        [HttpPost]
        [ValidateInput(false)]
        public JsonResult GiaiTrinhVuViec(GiaitrinhCommentViewModel data, List<HttpPostedFileBase> file)
        {
            var result = new JsonResultBO(true);
            try
            {
                if (file != null)
                {
                    foreach (var item in file)
                    {
                        string LogoFileExtension = Path.GetExtension(item.FileName);
                        List<string> ExtensionSupport = new List<string>() { ".png", ".jpg", ".jpeg", ".doc", ".docx", ".pdf" };
                        if (!ExtensionSupport.Contains(LogoFileExtension.ToLower()))
                        {

Hinet.Web/Areas/OrderInfoArea/Views/OrderInfo/Detail.cshtml
@{
	ViewBag.Title = "Quản lý thông tin giao dịch";
	Layout = "~/Views/Shared/_LayoutAce.cshtml";
	ViewBag.ModuleName = "Quản lý Quản lý thông tin giao dịch";
	ViewBag.PageName = "Thông tin Quản lý thông tin giao dịch";
	ViewBag.ModuleCode = "OrderInfo_detail";
}
@using Nami.Model.IdentityEntities
@using Nami.Model.Entities
@using Nami.Web.Areas.OrderInfoArea.Models
@using Nami.Service.Constant

@model DetailVM
@section ActionBarRight{
	<a href="/OrderInfoArea/OrderInfo/Index" class="btn btn-primary btn-sm">Quay lại</a>
}
<div class="tabbable">
	<ul class="nav nav-tabs padding-12 tab-color-blue background-blue" id="myTab4" style="text-align:center">
		<li class="active">
			<a data-toggle="tab" href="#PhanAnhInfo" aria-expanded="true">Thông tin giao dịch</a>
		</li>
		<li class="">
			<a data-toggle="tab" href="#GiaiTrinh" aria-expanded="false">Lịch sử giải trình</a>
		</li>
	</ul>
</div>

<div class="tab-content">
	<div id="PhanAnhInfo" class="tab-pane active">
		<div class="row">
			<div class="col-sm-12">
				<table class="table-info table100">
					<tr><td class="labelData">Id giao dịch</td><td colspan="3">@Model.objInfo.Id</td></tr>
					<tr><td class="labelData">Số tiền</td><td colspan="3" class="txt-number">@Model.objInfo.Amount</td></tr>
					<tr><td class="labelData">Nội dung giao dịch</td><td colspan="3">@Model.objInfo.OrderDescription</td></tr>
					<tr><td class="labelData">Mã ngân hàng</td><td colspan="3">@Model.objInfo.BankCodeName</td></tr>
					<tr><td class="labelData">Loại giao dịch</td><td colspan="3" style="color:@Model.objInfo.OrderTypeBGColor">@Model.objInfo.OrderTypeName</td></tr>
					<tr>
						<td class="labelData">Nhà trọ/khu trọ/phòng trọ</td>
						<td colspan="3">
							@if (!string.IsNullOrEmpty(Model.objInfo.UrlItem))
							{
								<a href="@Model.objInfo.UrlItem">@Model.objInfo.ItemName</a>
							}
						</td>
					</tr>
					<tr><td class="labelData">Loại</td><td colspan="3">@Model.objInfo.ItemTypeName</td></tr>
					<tr>
						<td class="labelData">Trạng thái thanh toán</td>
						<td colspan="3">
							@if (Model.objInfo.TrangThaiThanhToan == true)
							{
								<span class="green">Đã được xác nhận</span>
							}
							else
							{
								<span class="green">Chưa được xác nhân</span>
							}
						</td>
					</tr>

				</table>
			</div>
		</div>
	</div>


	<div id="GiaiTrinh" class="tab-pane">
		<div class="GiaiTrinhDetail">
			<div class="row" style="margin: 0px;">
				<div class="col-sm-6">
					@{
						if (Model.objGiaiTrinh != null)
						{
							if (Model.objGiaiTrinh.Count != 0)
							{
								foreach (var item in Model.objGiaiTrinh)
								{
									if (item.TypeHoSoGiaiTrinh == AccountTypeConstant.BussinessUser)
									{
										<div class="col-sm-11 GiaiTrinhListItemTextAdmin">
											<b>@item.NameHoSoGiaiTrinh (@String.Format("{0:g}", item.NgayGiaiTrinh))</b>
											@Html.Raw(item.GiaiTrinhComment)
											@if (item.ListFileAttackPhanAnh != null && item.ListFileAttackPhanAnh.Any())
											{
												<ul>
													@foreach (var fatc in item.ListFileAttackPhanAnh)
													{
														<li><a href="/@fatc.FileUrlGiaiTrinhPhanAnh" download><i class="fa fa-paperclip"></i>&nbsp;@Path.GetFileName(fatc.FileUrlGiaiTrinhPhanAnh)</a></li>
													}
												</ul>
											}
										</div>
										<div class="col-sm-1"></div>
									}
									else
									{
										<div class="col-sm-1"></div>
										<div class="col-sm-11 GiaiTrinhListItemTextEndUser">
											<b>@item.NameHoSoGiaiTrinh (@String.Format("{0:g}", item.NgayGiaiTrinh))</b>
											@Html.Raw(item.GiaiTrinhComment)
											@if (item.ListFileAttackPhanAnh != null && item.ListFileAttackPhanAnh.Any())
											{
												<ul>
													@foreach (var fatc in item.ListFileAttackPhanAnh)
													{
														<li><a href="/@fatc.FileUrlGiaiTrinhPhanAnh" download><i class="fa fa-paperclip"></i>&nbsp;@Path.GetFileName(fatc.FileUrlGiaiTrinhPhanAnh)</a></li>
													}
												</ul>
											}
										</div>
									}
								}
							}
							else
							{
								<div>Không có thông tin</div>
							}
						}
						else
						{
							<div>Không có thông tin</div>
						}
					}
				</div>
				<div class="col-sm-6">
					<div class="form-horizontal container-fluid comment">
						@using (Ajax.BeginForm("GiaiTrinhVuViec", "OrderInfo", new { @area = "OrderInfoArea" }, new AjaxOptions()
						{
							HttpMethod = "POST",
							OnFailure = "GiaiTrinhFalse",
							OnSuccess = "AjaxDone",
						}, new { id = "commentsform", enctype = "multipart/form-data" }))
						{
							<input type="hidden" name="id" value="@Model.objInfo.Id" />
							<input type="hidden" name="PhanAnhType" value="@ItemTypeConstant.Order" />
							<div class="row">

								<div class="col-sm-12 margin-bottom-12">
									<textarea class="form-control commentInput" cols="1" id="objComment_Comments" name="Comments" placeholder="Giải trình..." rows="1" style="overflow-y:hidden;"></textarea>
								</div>
								<div class="col-sm-12">
									<label>Tệp tin đính kèm</label>
									<input type="file" name="file" class="form-control" onchange="InputFile()" multiple>
									@*@Html.ValidationMessageFor(m => m.file, "", new { @class = "text-danger" })*@
									<p class="messageNote">Tệp tin đính kèm định dạng png, jpg, jpeg, doc, docx, pdf</p>
									<div>
										<button class="btn btn-primary giaitrinh-btn">
											<i class="fa fa-paper-plane"></i><p style="display: inline-block ">&nbsp;Gửi giải trình</p>
										</button>
									</div>
								</div>
							</div>
							<div class="clearfix"></div>
						}

					</div>
				</div>

			</div>
		</div>
	</div>
</div>
<div class="well well-sm">
	<div class="createTime">
		<h6>Khởi tạo lúc: <b>@Model.objInfo.CreatedDate</b>, bởi <a>@Model.objInfo.CreatedBy</a></h6>
	</div>
	<div class="updateTime">
		<h6>Thay đổi lần cuối lúc: <b>@Model.objInfo.UpdatedDate</b>, bởi <a>@Model.objInfo.UpdatedBy</a></h6>
	</div>
</div>

<script>
	$(".txt-number").autoNumeric({ digitGroupSeparator: '.', decimalCharacter: ',', vMin: 0, mDec: 2 });

	function AjaxDone(result) {
		if (result.Status) {
			location.reload();
		} else {
			NotiError(result.Message);
		}
	}
</script>
@Scripts.Render("~/bundles/jqueryval")

Hinet.Web/Areas/OrderInfoArea/Views/OrderInfo/_CreatePartial.cshtml
@using Nami.Model.IdentityEntities
@using Nami.Model.Entities
@using Nami.Web.Areas.OrderInfoArea.Models

@model CreateVM
@{

}

<div class="modal-dialog">
    @using (Ajax.BeginForm("Create", "OrderInfo", new { @area = "OrderInfoArea" }, new AjaxOptions()
    {
        HttpMethod = "POST",
        OnFailure = "AjaxFormError",
        OnSuccess = "AjaxFormSuccess",
    }, new { id = "createOrderInfoForm" }))
    {
        @Html.AntiForgeryToken()
        //HtmlHelper.UnobtrusiveJavaScriptEnabled = false;
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <div class="center">
                    <h4 class="modal-title">Tạo mới Quản lý thông tin giao dịch</h4>
                </div>
            </div>
            <div class="modal-body">
                <div class="form-horizontal">
				<div class="form-group">
				<label class="control-label col-sm-4">Id giao dịch <span class="red">*</span></label>
				<div class="col-sm-8">
				@Html.TextBoxFor(m => m.OrderId, new { @class = "form-control" })
				@Html.ValidationMessageFor(m => m.OrderId, "", new { @class = "text-danger" })
				</div>
				</div>
				<div class="form-group">
				<label class="control-label col-sm-4">Số tiền <span class="red">*</span></label>
				<div class="col-sm-8">
				@Html.TextBoxFor(m => m.Amount, new { @class = "form-control" })
				@Html.ValidationMessageFor(m => m.Amount, "", new { @class = "text-danger" })
				</div>
				</div>
				<div class="form-group">
				<label class="control-label col-sm-4">Nội dung giao dịch </label>
				<div class="col-sm-8">
				@Html.TextBoxFor(m => m.OrderDescription, new { @class = "form-control" })
				@Html.ValidationMessageFor(m => m.OrderDescription, "", new { @class = "text-danger" })
				</div>
				</div>
				<div class="form-group">
				<label class="control-label col-sm-4">Mã ngân hàng </label>
				<div class="col-sm-8">
				@Html.TextBoxFor(m => m.BankCode, new { @class = "form-control" })
				@Html.ValidationMessageFor(m => m.BankCode, "", new { @class = "text-danger" })
				</div>
				</div>
				<div class="form-group">
				<label class="control-label col-sm-4">Trạng thái <span class="red">*</span></label>
				<div class="col-sm-8">
				@Html.TextBoxFor(m => m.Status, new { @class = "form-control" })
				@Html.ValidationMessageFor(m => m.Status, "", new { @class = "text-danger" })
				</div>
				</div>
				<div class="form-group">
				<label class="control-label col-sm-4">Loại giao dịch </label>
				<div class="col-sm-8">
				@Html.TextBoxFor(m => m.OrderType, new { @class = "form-control" })
				@Html.ValidationMessageFor(m => m.OrderType, "", new { @class = "text-danger" })
				</div>
				</div>
				<div class="form-group">
				<label class="control-label col-sm-4">Id đối tượng <span class="red">*</span></label>
				<div class="col-sm-8">
				@Html.TextBoxFor(m => m.IdItem, new { @class = "form-control" })
				@Html.ValidationMessageFor(m => m.IdItem, "", new { @class = "text-danger" })
				</div>
				</div>
				<div class="form-group">
				<label class="control-label col-sm-4">Loại </label>
				<div class="col-sm-8">
				@Html.TextBoxFor(m => m.ItemType, new { @class = "form-control" })
				@Html.ValidationMessageFor(m => m.ItemType, "", new { @class = "text-danger" })
				</div>
				</div>
				<div class="form-group">
				<label class="control-label col-sm-4">Trạng thái thanh toán <span class="red">*</span></label>
				<div class="col-sm-8">
				@Html.TextBoxFor(m => m.TrangThaiThanhToan, new { @class = "form-control" })
				@Html.ValidationMessageFor(m => m.TrangThaiThanhToan, "", new { @class = "text-danger" })
				</div>
				</div>

                </div>
            </div>
            <div class="modal-footer center">
                <button type="submit" class="btn btn-primary">Hoàn thành</button>

                <button type="button" class="btn btn-default" data-dismiss="modal">Đóng</button>
            </div>
        </div>
    }
</div>

<script>




</script>
@Scripts.Render("~/bundles/jqueryval")

Hinet.Web/Areas/OrderInfoArea/Views/OrderInfo/_EditPartial.cshtml
@using Nami.Model.IdentityEntities
@using Nami.Model.IdentityEntities
@using Nami.Web.Areas.OrderInfoArea.Models

@model EditVM
@{ 

}
<div class="modal-dialog">
    @using (Ajax.BeginForm("Edit", "OrderInfo", new { @area = "OrderInfoArea" }, new AjaxOptions()
    {
        HttpMethod = "POST",
        OnFailure = "AjaxFormError",
        OnSuccess = "AjaxFormSuccess",
    }, new { id = "editOrderInfoForm" }))
    {
        @Html.AntiForgeryToken()
        //HtmlHelper.UnobtrusiveJavaScriptEnabled = false;
    <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <div class="center">
                    <h4 class="modal-title">Cập nhật Quản lý thông tin giao dịch</h4>
                </div>
            </div>
            <div class="modal-body">
                <div class="form-horizontal">
 			@Html.HiddenFor(x=>x.Id)
				<div class="form-group">
				<label class="control-label col-sm-4">Id giao dịch <span class="red">*</span></label>
				<div class="col-sm-8">
				@Html.TextBoxFor(m => m.OrderId, new { @class = "form-control" })
				@Html.ValidationMessageFor(m => m.OrderId, "", new { @class = "text-danger" })
				</div>
				</div>
				<div class="form-group">
				<label class="control-label col-sm-4">Số tiền <span class="red">*</span></label>
				<div class="col-sm-8">
				@Html.TextBoxFor(m => m.Amount, new { @class = "form-control" })
				@Html.ValidationMessageFor(m => m.Amount, "", new { @class = "text-danger" })
				</div>
				</div>
				<div class="form-group">
				<label class="control-label col-sm-4">Nội dung giao dịch </label>
				<div class="col-sm-8">
				@Html.TextBoxFor(m => m.OrderDescription, new { @class = "form-control" })
				@Html.ValidationMessageFor(m => m.OrderDescription, "", new { @class = "text-danger" })
				</div>
				</div>
				<div class="form-group">
				<label class="control-label col-sm-4">Mã ngân hàng </label>
				<div class="col-sm-8">
				@Html.TextBoxFor(m => m.BankCode, new { @class = "form-control" })
				@Html.ValidationMessageFor(m => m.BankCode, "", new { @class = "text-danger" })
				</div>
				</div>
				<div class="form-group">
				<label class="control-label col-sm-4">Trạng thái <span class="red">*</span></label>
				<div class="col-sm-8">
				@Html.TextBoxFor(m => m.Status, new { @class = "form-control" })
				@Html.ValidationMessageFor(m => m.Status, "", new { @class = "text-danger" })
				</div>
				</div>
				<div class="form-group">
				<label class="control-label col-sm-4">Loại giao dịch </label>
				<div class="col-sm-8">
				@Html.TextBoxFor(m => m.OrderType, new { @class = "form-control" })
				@Html.ValidationMessageFor(m => m.OrderType, "", new { @class = "text-danger" })
				</div>
				</div>
				<div class="form-group">
				<label class="control-label col-sm-4">Id đối tượng <span class="red">*</span></label>
				<div class="col-sm-8">
				@Html.TextBoxFor(m => m.IdItem, new { @class = "form-control" })
				@Html.ValidationMessageFor(m => m.IdItem, "", new { @class = "text-danger" })
				</div>
				</div>
				<div class="form-group">
				<label class="control-label col-sm-4">Loại </label>
				<div class="col-sm-8">
				@Html.TextBoxFor(m => m.ItemType, new { @class = "form-control" })
				@Html.ValidationMessageFor(m => m.ItemType, "", new { @class = "text-danger" })
				</div>
				</div>
				<div class="form-group">
				<label class="control-label col-sm-4">Trạng thái thanh toán <span class="red">*</span></label>
				<div class="col-sm-8">
				@Html.TextBoxFor(m => m.TrangThaiThanhToan, new { @class = "form-control" })
				@Html.ValidationMessageFor(m => m.TrangThaiThanhToan, "", new { @class = "text-danger" })
				</div>
				</div>

 

                </div>
            </div>
            <div class="modal-footer center">
                <button type="submit" class="btn btn-primary">Hoàn thành</button>

                <button type="button" class="btn btn-default" data-dismiss="modal">Đóng</button>
            </div>
        </div>
    }
</div>
<script>

</script>
@Scripts.Render("~/bundles/jqueryval")