Hinet.Web/Areas/MapLocationInfoArea/Controllers/MapLocationInfoController.cs
using AutoMapper;
using CommonHelper.String;
using CommonHelper.Upload;
using log4net;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Nami.Model.IdentityEntities;
using Nami.Model.Entities;
using Nami.Service.Common;
using Nami.Service.Constant;
using Nami.Web.Areas.MapLocationInfoArea.Models;
using Nami.Web.Filters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using Nami.Web.Filters;
using Nami.Service.MapLocationInfoService;
using Nami.Service.MapLocationInfoService.Dto;



namespace Nami.Web.Areas.MapLocationInfoArea.Controllers
{
    public class MapLocationInfoController : BaseController
    {
        private readonly ILog _Ilog;
        private readonly IMapper _mapper;
        public const string permissionIndex = "MapLocationInfo_index";
        public const string permissionCreate = "MapLocationInfo_create";
        public const string permissionEdit = "MapLocationInfo_edit";
        public const string permissionDelete = "MapLocationInfo_delete";
        public const string permissionImport = "MapLocationInfo_Inport";
        public const string permissionExport = "MapLocationInfo_export";
        public const string searchKey = "MapLocationInfoPageSearchModel";
        private readonly IMapLocationInfoService _MapLocationInfoService;


        public MapLocationInfoController(IMapLocationInfoService MapLocationInfoService, ILog Ilog,

            IMapper mapper
            )
        {
            _MapLocationInfoService = MapLocationInfoService;
            _Ilog = Ilog;
            _mapper = mapper;

        }
        // GET: MapLocationInfoArea/MapLocationInfo
        //[PermissionAccess(Code = permissionIndex)]
        public ActionResult Index()
        {
            var listData = _MapLocationInfoService.GetDaTaByPage(null);
            SessionManager.SetValue(searchKey, null);
            return View(listData);
        }

        [HttpPost]
        public JsonResult getData(int indexPage, string sortQuery, int pageSize)
        {
            var searchModel = SessionManager.GetValue(searchKey) as MapLocationInfoSearchDto;
            if (!string.IsNullOrEmpty(sortQuery))
            {
                if (searchModel == null)
                {
                    searchModel = new MapLocationInfoSearchDto();
                }
                searchModel.sortQuery = sortQuery;
                if (pageSize > 0)
                {
                    searchModel.pageSize = pageSize;
                }
                SessionManager.SetValue(searchKey, searchModel);
            }
            var data = _MapLocationInfoService.GetDaTaByPage(searchModel, indexPage, pageSize);
            return Json(data);
        }
        public PartialViewResult Create()
        {
            var myModel = new CreateVM();

            return PartialView("_CreatePartial", myModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public JsonResult Create(CreateVM model)
        {
            var result = new JsonResultBO(true, "Tạo Vị trí bản đồ thành công");
            try
            {
                if (ModelState.IsValid)
                {
                    var EntityModel = _mapper.Map<MapLocationInfo>(model);
                    _MapLocationInfoService.Create(EntityModel);

                }

            }
            catch (Exception ex)
            {
                result.MessageFail(ex.Message);
                _Ilog.Error("Lỗi tạo mới Vị trí bản đồ", ex);
            }
            return Json(result);
        }

        public PartialViewResult Edit(long id)
        {
            var myModel = new EditVM();

            var obj= _MapLocationInfoService.GetById(id);
            if (obj== null)
            {
                throw new HttpException(404, "Không tìm thấy thông tin");
            }

            myModel = _mapper.Map(obj, myModel);
            return PartialView("_EditPartial", myModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]

        public JsonResult Edit(EditVM model)
        {
            var result = new JsonResultBO(true);
            try
            {
                if (ModelState.IsValid)
                {

                    var obj = _MapLocationInfoService.GetById(model.Id);
                    if (obj == null)
                    {
                        throw new Exception("Không tìm thấy thông tin");
                    }

                    obj= _mapper.Map(model, obj);
                    _MapLocationInfoService.Update(obj);
                    
                }
            }
            catch (Exception ex)
            {
                result.Status = false;
                result.Message = "Không cập nhật được";
                _Ilog.Error("Lỗi cập nhật thông tin Vị trí bản đồ", ex);
            }
            return Json(result);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult searchData(MapLocationInfoSearchDto form)
        {
            var searchModel = SessionManager.GetValue(searchKey) as MapLocationInfoSearchDto;

            if (searchModel == null)
            {
                searchModel = new MapLocationInfoSearchDto();
                searchModel.pageSize = 20;
            }

            SessionManager.SetValue((searchKey) , searchModel);

            var data = _MapLocationInfoService.GetDaTaByPage(searchModel, 1, searchModel.pageSize);
            return Json(data);
        }

        [HttpPost]
        public JsonResult Delete(long id)
        {
            var result = new JsonResultBO(true, "Xóa Vị trí bản đồ thành công");
            try
            {
                var user = _MapLocationInfoService.GetById(id);
                if (user == null)
                {
                    throw new Exception("Không tìm thấy thông tin để xóa");
                }
                _MapLocationInfoService.Delete(user);
            }
            catch (Exception ex)
            {
                result.MessageFail("Không thực hiện được");
                _Ilog.Error("Lỗi khi xóa tài khoản id=" + id, ex);
            }
            return Json(result);
        }

        
        public ActionResult Detail(long id)
        {
            var model = new DetailVM();
            model.objInfo = _MapLocationInfoService.GetById(id);
            return View(model);
        }

        
    }
}

Hinet.Web/Areas/MapLocationInfoArea/Views/MapLocationInfo/Detail.cshtml
@{
    ViewBag.Title = "Vị trí bản đồ";
    Layout = "~/Views/Shared/_LayoutAce.cshtml";
    ViewBag.ModuleName = "Quản lý Vị trí bản đồ";
    ViewBag.PageName = "Thông tin Vị trí bản đồ";
    ViewBag.ModuleCode = "MapLocationInfo_detail";
}
@using Nami.Model.IdentityEntities
@using Nami.Model.Entities
@using Nami.Web.Areas.MapLocationInfoArea.Models

@model DetailVM
@section ActionBarRight{
    <a href="/MapLocationInfoArea/MapLocationInfo/Index" class="btn btn-primary btn-sm">Quay lại</a>
}

<div class="row">
     <div class="col-sm-12">
           <table class="table-info">
           	
<tr><td>Id khu trọ</td><td>@Model.objInfo.BuildingsId</td></tr>
<tr><td>Id phòng</td><td>@Model.objInfo.RoomsId</td></tr>
<tr><td>Loại đối tượng</td><td>@Model.objInfo.ItemTypeCode</td></tr>
<tr><td>Tọa độ X</td><td>@Model.objInfo.Xlocation</td></tr>
<tr><td>Tạo độ Y</td><td>@Model.objInfo.Ylocation</td></tr>
<tr><td>Ngày tạo</td><td>@Model.objInfo.CreatedDate</td></tr>
<tr><td>Người tạo</td><td>@Model.objInfo.CreatedBy</td></tr>
<tr><td>Ngày sửa</td><td>@Model.objInfo.UpdatedDate</td></tr>
<tr><td>Người sửa</td><td>@Model.objInfo.UpdatedBy</td></tr>

           </table>
     </div>
    
</div>

<script>

</script>
@Scripts.Render("~/bundles/jqueryval")

Hinet.Web/Areas/MapLocationInfoArea/Views/MapLocationInfo/Index.cshtml
@{
    ViewBag.Title = "Vị trí bản đồ";
    Layout = "~/Views/Shared/_LayoutAce.cshtml";
    ViewBag.ModuleName = "Quản lý Vị trí bản đồ";
    ViewBag.PageName = "Danh sách Vị trí bản đồ";
    ViewBag.ModuleCode = "MapLocationInfo_index";

}
@using Nami.Model.IdentityEntities;
@using Nami.Model.Entities;
@using Newtonsoft.Json;
@using Nami.Service.Common;
@using Nami.Service.MapLocationInfoService.Dto;
@model PageListResultBO<MapLocationInfoDto>
@{
    var lstData = Html.Raw(JsonConvert.SerializeObject(Model.ListItem));
}



@section ActionBarRight{
    <a href="#collapseDiv" class="btn btn-sm btn-primary" aria-controls="collapsePanel" data-toggle="collapse" role="button">
        Tìm kiếm
    </a>
    <a href="javascript:void(0)" onclick="CreateAction('/MapLocationInfoArea/MapLocationInfo/Create')" class="btn btn-primary btn-sm">Thêm mới</a>
}
@Html.Partial("_SearchPartial")

<div id="tbl-MapLocationInfo" class="hntbl-cover">
    <table class="Nami-table table table-striped table-hover" cellspacing="0" width="100%">
        <thead>
            <tr>
                <th></th>
                <th>#</th>
				<th>Id khu trọ</th>
				<th>Id phòng</th>
				<th>Loại đối tượng</th>
				<th>Tọa độ X</th>
				<th>Tạo độ Y</th>

                <th></th>
            </tr>
        </thead>
        <tbody></tbody>
    </table>
</div>

@section scripts{
    <script>
        var lstData = eval(@lstData);
        var moduleTableSelector="#tbl-MapLocationInfo";
        function pagefunction(){
            var conf=[
                {
                    tdClass:"center width50",
                    isSort:false,
                    nameModel: "",
                    isCounter:true,
                    content: function (data) {
                        return "<input type='checkbox'/>"
                    }
                },
				{
					isSort:true,
					nameModel:'BuildingsId',
					content: function (data) {
					return data.BuildingsId
				}
				},
				{
					isSort:true,
					nameModel:'RoomsId',
					content: function (data) {
					return data.RoomsId
				}
				},
				{
					isSort:true,
					nameModel:'ItemTypeCode',
					content: function (data) {
					return data.ItemTypeCode
				}
				},
				{
					isSort:true,
					nameModel:'Xlocation',
					content: function (data) {
					return data.Xlocation
				}
				},
				{
					isSort:true,
					nameModel:'Ylocation',
					content: function (data) {
					return data.Ylocation
				}
				},

                   {
                       isSort:false,
                       nameModel:"",
                       tdClass:"center",
                       content: function (data) {
                           var result = `<div class="btn-group">
                               <button data-toggle="dropdown" class="btn btn-xs btn-primary btn-white dropdown-toggle" aria-expanded="false">Thao tác<i class="ace-icon fa fa-angle-down icon-on-right"></i>
                               </button>

                               <ul class="dropdown-menu">`;
                           result += "<li><a href='javascript:void(0)' onclick='EditAction(\"/MapLocationInfoArea/MapLocationInfo/Edit/" + data.Id + "\")'   title = 'Chỉnh sửa'><i class='glyphicon glyphicon-edit'> </i> Sửa thông tin</a> </li>";
                           result += "<li><a href='javascript:void(0)' onclick='DeleteAction(\"/MapLocationInfoArea/MapLocationInfo/Delete/" + data.Id + "\")'  title = 'Xóa'><i class=' glyphicon glyphicon-remove' style='color:red'> </i> Xóa</a></li>";
                           result += "</ul></div>";
                           return result;
                       }
                   },

            ];


            var getdatafunc=function(page,sortQuery,pageSize){
                $.ajax({
                    url: '/MapLocationInfoArea/MapLocationInfo/getData',
                    type: 'post',
                    cache: false,
                    data:{"indexPage":page,"sortQuery":sortQuery,"pageSize":pageSize},
                    success: function (data) {
                        $(moduleTableSelector).NamiTable("data",{
                            pageSize:pageSize!=-1?pageSize:data.Count,
                            pageIndex:page,
                            pagecount: data.TotalPage,
                            recordCount: data.Count,
                            listItem: data.ListItem,});
                    },
                    error: function (err) {
                        CommonJS.alert(xhr.responseText);
                    }
                });

            }

            var tblData=$("#tbl-MapLocationInfo").NamiTable("init",{
                pageSizeList:{size:[20,50,100,-1],label:['20','50','100','Tất cả']},
                pagecount: @Model.TotalPage,
                recordCount: @Model.Count,
                actionToolBar:'<a href=\"#collapseDiv\" aria-controls=\"collapsePanel\" data-toggle=\"collapse\" role=\"button\" class="btn btn-primary btn-xs"><i class="fa fa-search"></i> Tìm kiếm</a>',
                getData:getdatafunc,
                listItem:lstData,
                config:conf
            });

        }

        function AfterSussessActionAjaxform(){
            $(moduleTableSelector).NamiTable("reload");
        }
        function AjaxSearchSuccess(rs) {
            $(moduleTableSelector).NamiTable("data", {
                pageIndex: 1,
                pagecount: rs.TotalPage,
                recordCount: rs.Count,
                listItem: rs.ListItem,
            });
        }
        pagefunction();
    </script>
}

Hinet.Web/Areas/MapLocationInfoArea/Views/MapLocationInfo/_CreatePartial.cshtml
@using Nami.Model.IdentityEntities
@using Nami.Model.Entities
@using Nami.Web.Areas.MapLocationInfoArea.Models

@model CreateVM
@{

}

<div class="modal-dialog">
    @using (Ajax.BeginForm("Create", "MapLocationInfo", new { @area = "MapLocationInfoArea" }, new AjaxOptions()
    {
        HttpMethod = "POST",
        OnFailure = "AjaxFormError",
        OnSuccess = "AjaxFormSuccess",
    }, new { id = "createMapLocationInfoForm" }))
    {
        @Html.AntiForgeryToken()
        //HtmlHelper.UnobtrusiveJavaScriptEnabled = false;
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <div class="center">
                    <h4 class="modal-title">Tạo mới Vị trí bản đồ</h4>
                </div>
            </div>
            <div class="modal-body">
                <div class="form-horizontal">
				<div class="form-group">
				<label class="control-label col-sm-4">Id khu trọ </label>
				<div class="col-sm-8">
				@Html.TextBoxFor(m => m.BuildingsId, new { @class = "form-control" })
				@Html.ValidationMessageFor(m => m.BuildingsId, "", new { @class = "text-danger" })
				</div>
				</div>
				<div class="form-group">
				<label class="control-label col-sm-4">Id phòng </label>
				<div class="col-sm-8">
				@Html.TextBoxFor(m => m.RoomsId, new { @class = "form-control" })
				@Html.ValidationMessageFor(m => m.RoomsId, "", new { @class = "text-danger" })
				</div>
				</div>
				<div class="form-group">
				<label class="control-label col-sm-4">Loại đối tượng </label>
				<div class="col-sm-8">
				@Html.TextBoxFor(m => m.ItemTypeCode, new { @class = "form-control" })
				@Html.ValidationMessageFor(m => m.ItemTypeCode, "", new { @class = "text-danger" })
				</div>
				</div>
				<div class="form-group">
				<label class="control-label col-sm-4">Tọa độ X </label>
				<div class="col-sm-8">
				@Html.TextBoxFor(m => m.Xlocation, new { @class = "form-control" })
				@Html.ValidationMessageFor(m => m.Xlocation, "", new { @class = "text-danger" })
				</div>
				</div>
				<div class="form-group">
				<label class="control-label col-sm-4">Tạo độ Y </label>
				<div class="col-sm-8">
				@Html.TextBoxFor(m => m.Ylocation, new { @class = "form-control" })
				@Html.ValidationMessageFor(m => m.Ylocation, "", new { @class = "text-danger" })
				</div>
				</div>

                </div>
            </div>
            <div class="modal-footer center">
                <button type="submit" class="btn btn-primary">Hoàn thành</button>

                <button type="button" class="btn btn-default" data-dismiss="modal">Đóng</button>
            </div>
        </div>
    }
</div>

<script>




</script>
@Scripts.Render("~/bundles/jqueryval")

Hinet.Web/Areas/MapLocationInfoArea/Views/MapLocationInfo/_EditPartial.cshtml
@using Nami.Model.IdentityEntities
@using Nami.Model.IdentityEntities
@using Nami.Web.Areas.MapLocationInfoArea.Models

@model EditVM
@{ 

}
<div class="modal-dialog">
    @using (Ajax.BeginForm("Edit", "MapLocationInfo", new { @area = "MapLocationInfoArea" }, new AjaxOptions()
    {
        HttpMethod = "POST",
        OnFailure = "AjaxFormError",
        OnSuccess = "AjaxFormSuccess",
    }, new { id = "editMapLocationInfoForm" }))
    {
        @Html.AntiForgeryToken()
        //HtmlHelper.UnobtrusiveJavaScriptEnabled = false;
    <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <div class="center">
                    <h4 class="modal-title">Cập nhật Vị trí bản đồ</h4>
                </div>
            </div>
            <div class="modal-body">
                <div class="form-horizontal">
 			@Html.HiddenFor(x=>x.Id)
				<div class="form-group">
				<label class="control-label col-sm-4">Id khu trọ </label>
				<div class="col-sm-8">
				@Html.TextBoxFor(m => m.BuildingsId, new { @class = "form-control" })
				@Html.ValidationMessageFor(m => m.BuildingsId, "", new { @class = "text-danger" })
				</div>
				</div>
				<div class="form-group">
				<label class="control-label col-sm-4">Id phòng </label>
				<div class="col-sm-8">
				@Html.TextBoxFor(m => m.RoomsId, new { @class = "form-control" })
				@Html.ValidationMessageFor(m => m.RoomsId, "", new { @class = "text-danger" })
				</div>
				</div>
				<div class="form-group">
				<label class="control-label col-sm-4">Loại đối tượng </label>
				<div class="col-sm-8">
				@Html.TextBoxFor(m => m.ItemTypeCode, new { @class = "form-control" })
				@Html.ValidationMessageFor(m => m.ItemTypeCode, "", new { @class = "text-danger" })
				</div>
				</div>
				<div class="form-group">
				<label class="control-label col-sm-4">Tọa độ X </label>
				<div class="col-sm-8">
				@Html.TextBoxFor(m => m.Xlocation, new { @class = "form-control" })
				@Html.ValidationMessageFor(m => m.Xlocation, "", new { @class = "text-danger" })
				</div>
				</div>
				<div class="form-group">
				<label class="control-label col-sm-4">Tạo độ Y </label>
				<div class="col-sm-8">
				@Html.TextBoxFor(m => m.Ylocation, new { @class = "form-control" })
				@Html.ValidationMessageFor(m => m.Ylocation, "", new { @class = "text-danger" })
				</div>
				</div>

 

                </div>
            </div>
            <div class="modal-footer center">
                <button type="submit" class="btn btn-primary">Hoàn thành</button>

                <button type="button" class="btn btn-default" data-dismiss="modal">Đóng</button>
            </div>
        </div>
    }
</div>
<script>

</script>
@Scripts.Render("~/bundles/jqueryval")

Hinet.Web/Areas/MapLocationInfoArea/Views/MapLocationInfo/_SearchPartial.cshtml
<div id="collapseDiv" class="panel-collapse collapse" aria-expanded="false" role="tabpanel">
    <div class="well SearchBox">

        @using (Ajax.BeginForm("searchData", "MapLocationInfo", new { Area = "MapLocationInfoArea" },
            new AjaxOptions()
            {
                HttpMethod = "POST",
                OnFailure = "AjaxFormError",
                OnSuccess = "AjaxSearchSuccess",
            }, new { }))
        {
            @Html.AntiForgeryToken()
        <div class="row row-block">

            <div class="col-md-12 center" style=" margin-top:20px;">
                <button id="btnSearch" type="submit" class="btn btn-labeled btn-primary btn-sm">
                    <span class="btn-label">
                        <i class="glyphicon glyphicon-search"></i>
                    </span>
                    Tìm kiếm
                </button>

                <a aria-expanded="false" href="#collapseDiv" data-toggle="collapse" role="button" class="btn btn-labeled btn-danger btn-sm">
                    <span class="btn-label"><i class="glyphicon glyphicon-remove"></i></span>
                    Đóng
                </a>
            </div>
        </div>

        }
    </div>
</div>