Hinet.Web/Areas/NotificationArea/Controllers/NotificationController.cs
using AutoMapper;
using CommonHelper.String;
using CommonHelper.Upload;
using log4net;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Nami.Model.IdentityEntities;
using Nami.Model.Entities;
using Nami.Service.Common;
using Nami.Service.Constant;
using Nami.Web.Areas.NotificationArea.Models;
using Nami.Web.Filters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using Nami.Web.Filters;
using Nami.Service.NotificationService;
using Nami.Service.NotificationService.Dto;
using Nami.Web.Core;

namespace Nami.Web.Areas.NotificationArea.Controllers
{
    public class NotificationController : BaseController
    {
        private readonly ILog _Ilog;
        private readonly IMapper _mapper;
        public const string permissionIndex = "Notification_index";
        public const string permissionCreate = "Notification_create";
        public const string permissionEdit = "Notification_edit";
        public const string permissionDelete = "Notification_delete";
        public const string permissionImport = "Notification_Inport";
        public const string permissionExport = "Notification_export";
        public const string searchKey = "NotificationPageSearchModel";
        private readonly INotificationService _NotificationService;


        public NotificationController(INotificationService NotificationService, ILog Ilog,

            IMapper mapper
            )
        {
            _NotificationService = NotificationService;
            _Ilog = Ilog;
            _mapper = mapper;

        }
        // GET: NotificationArea/Notification
        //[PermissionAccess(Code = permissionIndex)]
        public ActionResult Index()
        {

            var listData = _NotificationService.GetDaTaByPage(CurrentUserId,null);
            SessionManager.SetValue(searchKey, null);
            return View(listData);
        }

        [HttpPost]
        public JsonResult getData(int indexPage, string sortQuery, int pageSize)
        {
            var searchModel = SessionManager.GetValue(searchKey) as NotificationSearchDto;
            if (!string.IsNullOrEmpty(sortQuery))
            {
                if (searchModel == null)
                {
                    searchModel = new NotificationSearchDto();
                }
                searchModel.sortQuery = sortQuery;
                if (pageSize > 0)
                {
                    searchModel.pageSize = pageSize;
                }
                SessionManager.SetValue(searchKey, searchModel);
            }
            var data = _NotificationService.GetDaTaByPage(CurrentUserId,searchModel, indexPage, pageSize);
            return Json(data);
        }
        public PartialViewResult Create()
        {
            var myModel = new CreateVM();

            return PartialView("_CreatePartial", myModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public JsonResult Create(CreateVM model)
        {
            var result = new JsonResultBO(true, "Tạo Thông báo hệ thống thành công");
            try
            {
                if (ModelState.IsValid)
                {
                    model.IsRead = false;
                    var EntityModel = _mapper.Map<Notification>(model);
                    _NotificationService.Create(EntityModel);
                    NotificationProvider.SendMessage(EntityModel);
                }

            }
            catch (Exception ex)
            {
                result.MessageFail(ex.Message);
                _Ilog.Error("Lỗi tạo mới Thông báo hệ thống", ex);
            }
            return Json(result);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult searchData(NotificationSearchDto form)
        {
            var searchModel = SessionManager.GetValue(searchKey) as NotificationSearchDto;

            if (searchModel == null)
            {
                searchModel = new NotificationSearchDto();
                searchModel.pageSize = 20;
            }
            searchModel.IsReadFilter = form.IsReadFilter;
            searchModel.FromUserFilter = form.FromUserFilter;
            searchModel.ToUserFilter = form.ToUserFilter;
            searchModel.MessageFilter = form.MessageFilter;
            searchModel.TypeFilter = form.TypeFilter;

            SessionManager.SetValue((searchKey), searchModel);

            var data = _NotificationService.GetDaTaByPage(CurrentUserId,searchModel, 1, searchModel.pageSize);
            return Json(data);
        }

        [HttpPost]
        public JsonResult Delete(long id)
        {
            var result = new JsonResultBO(true, "Xóa Thông báo hệ thống thành công");
            try
            {
                var user = _NotificationService.GetById(id);
                if (user == null)
                {
                    throw new Exception("Không tìm thấy thông tin để xóa");
                }
                _NotificationService.Delete(user);
            }
            catch (Exception ex)
            {
                result.MessageFail("Không thực hiện được");
                _Ilog.Error("Lỗi khi xóa tài khoản id=" + id, ex);
            }
            return Json(result);
        }


        public ActionResult Detail(long id)
        {
            var model = new DetailVM();
            model.objInfo = _NotificationService.GetById(id);
            return View(model);
        }

        public PartialViewResult ShowNotification()
        {
            var listNotification = _NotificationService.GetByUserId(CurrentUserId, 10);
            return PartialView(listNotification);
        }

        public ActionResult ReadNotification(long id)
        {
            var Noti = _NotificationService.GetById(id);
            Noti.IsRead = true;
            _NotificationService.Update(Noti);
            return Redirect(Noti.Link);
        }
    }
}

Hinet.Web/Areas/NotificationArea/Views/Notification/Detail.cshtml
@{
    ViewBag.Title = "Thông báo hệ thống";
    Layout = "~/Views/Shared/_LayoutAce.cshtml";
    ViewBag.ModuleName = "Quản lý Thông báo hệ thống";
    ViewBag.PageName = "Thông tin Thông báo hệ thống";
    ViewBag.ModuleCode = "Notification_detail";
}
@using Nami.Model.IdentityEntities
@using Nami.Model.Entities
@using Nami.Web.Areas.NotificationArea.Models

@model DetailVM
@section ActionBarRight{
    <a href="/NotificationArea/Notification/Index" class="btn btn-primary btn-sm">Quay lại</a>
}

<div class="row">
     <div class="col-sm-12">
           <table class="table-info">
           	
<tr><td>Ngày tạo</td><td>@Model.objInfo.CreatedDate</td></tr>
<tr><td>Ngày sử</td><td>@Model.objInfo.UpdatedDate</td></tr>
<tr><td>Đã đọc</td><td>@Model.objInfo.IsRead</td></tr>
<tr><td>Người gửi</td><td>@Model.objInfo.FromUser</td></tr>
<tr><td>Người nhận</td><td>@Model.objInfo.ToUser</td></tr>
<tr><td>Nội dung</td><td>@Model.objInfo.Message</td></tr>
<tr><td>Liên kết</td><td>@Model.objInfo.Link</td></tr>
<tr><td>Loại</td><td>@Model.objInfo.Type</td></tr>
<tr><td>Người tạo</td><td>@Model.objInfo.CreatedBy</td></tr>
<tr><td>Người sửa</td><td>@Model.objInfo.UpdatedBy</td></tr>

           </table>
     </div>
    
</div>

<script>

</script>
@Scripts.Render("~/bundles/jqueryval")

Hinet.Web/Areas/NotificationArea/Views/Notification/Index.cshtml
@{
    ViewBag.Title = "Thông báo hệ thống";
    Layout = "~/Views/Shared/_LayoutAce.cshtml";
    ViewBag.ModuleName = "Quản lý Thông báo hệ thống";
    ViewBag.PageName = "Danh sách Thông báo hệ thống";
    ViewBag.ModuleCode = "Notification_index";

}
@using Nami.Model.IdentityEntities;
@using Nami.Model.Entities;
@using Newtonsoft.Json;
@using Nami.Service.Common;
@using Nami.Service.NotificationService.Dto;
@model PageListResultBO<NotificationDto>
@{
    var lstData = Html.Raw(JsonConvert.SerializeObject(Model.ListItem));
}



@section ActionBarRight{
    @*<a href="#collapseDiv" class="btn btn-sm btn-primary" aria-controls="collapsePanel" data-toggle="collapse" role="button">
        Tìm kiếm
    </a>*@
}
@Html.Partial("_SearchPartial")

<div id="tbl-Notification" class="hntbl-cover">
    <div class="hntbl-cover-tableScroll">
        <table class="Nami-table table table-striped table-hover" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th></th>
                    <th>#</th>
                    <th></th>
                    <th>Người gửi</th>
                    <th>Nội dung</th>
                    <th>Liên kết</th>
                    <th>Loại</th>

                    <th></th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>
</div>

    @section scripts{
        <script>
        var lstData = eval(@lstData);
        var moduleTableSelector="#tbl-Notification";
        function pagefunction(){
            var conf=[
                {
                    tdClass:"center width50",
                    isSort:false,
                    nameModel: "",
                    isCounter:true,
                    content: function (data) {
                        return "<input type='checkbox'/>"
                    }
                },
				{
					isSort:true,
					nameModel:'Id',
					content: function (data) {
					return data.Id
				}
				},
				{
					isSort:true,
					nameModel:'FromUser',
					content: function (data) {
					return data.FromUserName
				}
				},
				{
					isSort:true,
					nameModel:'Message',
					content: function (data) {
					return data.Message
				}
				},
				{
					isSort:true,
					nameModel:'Link',
					content: function (data) {
					return data.Link
				}
				},
				{
					isSort:true,
					nameModel:'Type',
					content: function (data) {
					return data.Type
				}
				},

                   {
                       isSort:false,
                       nameModel:"",
                       tdClass:"center dropdowntt",
                       content: function (data) {
                           var result = `<div class="btn-group">
                               <button data-toggle="dropdown" class="btn btn-xs btn-primary btn-white dropdown-toggle" aria-expanded="false">Thao tác<i class="ace-icon fa fa-angle-down icon-on-right"></i>
                               </button>

                               <ul class="dropdown-menu">`;                           
                           result += "<li><a href='javascript:void(0)' onclick='DeleteAction(\"/NotificationArea/Notification/Delete/" + data.Id + "\")'  title = 'Xóa'><i class=' glyphicon glyphicon-remove' style='color:red'> </i> Xóa</a></li>";
                           result += "</ul></div>";
                           return result;
                       }
                   },

            ];


            var getdatafunc=function(page,sortQuery,pageSize){
                $.ajax({
                    url: '/NotificationArea/Notification/getData',
                    type: 'post',
                    cache: false,
                    data:{"indexPage":page,"sortQuery":sortQuery,"pageSize":pageSize},
                    success: function (data) {
                        $(moduleTableSelector).NamiTable("data",{
                            pageSize:pageSize!=-1?pageSize:data.Count,
                            pageIndex:page,
                            pagecount: data.TotalPage,
                            recordCount: data.Count,
                            listItem: data.ListItem,});
                    },
                    error: function (err) {
                        CommonJS.alert(xhr.responseText);
                    }
                });

            }

            var tblData=$("#tbl-Notification").NamiTable("init",{
                pageSizeList:{size:[20,50,100,-1],label:['20','50','100','Tất cả']},
                pagecount: @Model.TotalPage,
                recordCount: @Model.Count,
                actionToolBar:'<a href=\"#collapseDiv\" aria-controls=\"collapsePanel\" data-toggle=\"collapse\" role=\"button\" class="btn btn-primary btn-xs"><i class="fa fa-search"></i> Tìm kiếm</a>',
                getData:getdatafunc,
                listItem:lstData,
                config:conf
            });

        }

        function AfterSussessActionAjaxform(){
            $(moduleTableSelector).NamiTable("reload");
        }
        function AjaxSearchSuccess(rs) {
            $(moduleTableSelector).NamiTable("data", {
                pageIndex: 1,
                pagecount: rs.TotalPage,
                recordCount: rs.Count,
                listItem: rs.ListItem,
            });
        }
        pagefunction();
        </script>
    }

Hinet.Web/Areas/NotificationArea/Views/Notification/ShowNotification.cshtml
@using Nami.Service.Common

@model PageListResultBO<Nami.Model.Entities.Notification>

<a data-toggle="dropdown" class="dropdown-toggle" href="#">
    <i class="ace-icon fa fa-bell icon-animated-bell"></i>
    <span class="badge badge-important">@Model.Count</span>
</a>

<ul class="dropdown-menu-right dropdown-navbar navbar-pink dropdown-menu dropdown-caret dropdown-close">
    <li class="dropdown-header">
        <i class="ace-icon fa fa-exclamation-triangle"></i>
        @Model.Count <span>Thông báo</span>
    </li>

    <li class="dropdown-content ace-scroll" style="position: relative;">

        <div class="scroll-content123" style="max-height: 200px;overflow-y:scroll;">
            <ul class="dropdown-menu dropdown-navbar navbar-pink">
                @foreach (var item in Model.ListItem)
                {
                    <li>
                        <a href="/NotificationArea/Notification/ReadNotification/@item.Id">
                            <div class="clearfix">
                                <span class="pull-left">
                                    <i class="btn btn-xs no-hover btn-pink fa fa-globe"></i>
                                    @item.Message
                                </span>
                                @{
                                    var timeSpan = (TimeSpan)(DateTime.Now - item.CreatedDate);
                                    if (timeSpan.TotalMinutes < 2)
                                    {
                                        <small class="pull-right"><i>Vừa xong</i></small>
                                    }
                                    else if (timeSpan.TotalMinutes < 60)
                                    {
                                        <small class="pull-right"><i>@Math.Round(timeSpan.TotalMinutes) phút trước</i></small>
                                    }
                                    else if (timeSpan.TotalHours < 24)
                                    {
                                        <small class="pull-right"><i>@Math.Round(timeSpan.TotalHours) giờ trước</i></small>
                                    }
                                    else
                                    {
                                        <small class="pull-right"><i>@string.Format("{0:dd/MM/yyyy HH:mm:ss}", item.CreatedDate) </i></small>
                                    }

                                }

                            </div>

                        </a>
                    </li>
                }
                @if (!Model.ListItem.Any())
                {
                    <li>
                        <div class="clearfix">
                            <span class="pull-left">
                                Không có thông báo mới
                            </span>
                  
                        </div>

                    </li>
                }

            </ul>
        </div>
    </li>

    <li class="dropdown-footer">
        <a href="/NotificationArea/Notification">
            Xem tất cả
            <i class="ace-icon fa fa-arrow-right"></i>
        </a>
    </li>
</ul>

Hinet.Web/Areas/NotificationArea/Views/Notification/_CreatePartial.cshtml
@using Nami.Model.IdentityEntities
@using Nami.Model.Entities
@using Nami.Web.Areas.NotificationArea.Models

@model CreateVM
@{

}

<div class="modal-dialog">
    @using (Ajax.BeginForm("Create", "Notification", new { @area = "NotificationArea" }, new AjaxOptions()
    {
        HttpMethod = "POST",
        OnFailure = "AjaxFormError",
        OnSuccess = "AjaxFormSuccess",
    }, new { id = "createNotificationForm" }))
    {
        @Html.AntiForgeryToken()
        //HtmlHelper.UnobtrusiveJavaScriptEnabled = false;
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <div class="center">
                    <h4 class="modal-title">Tạo mới Thông báo hệ thống</h4>
                </div>
            </div>
            <div class="modal-body">
                <div class="form-horizontal">
               
                    <div class="form-group">
                        <label class="control-label col-sm-4">Người gửi </label>
                        <div class="col-sm-8">
                            @Html.TextBoxFor(m => m.FromUser, new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.FromUser, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-4">Người nhận </label>
                        <div class="col-sm-8">
                            @Html.TextBoxFor(m => m.ToUser, new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.ToUser, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-4">Nội dung <span class="red">*</span></label>
                        <div class="col-sm-8">
                            @Html.TextBoxFor(m => m.Message, new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.Message, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-4">Liên kết </label>
                        <div class="col-sm-8">
                            @Html.TextBoxFor(m => m.Link, new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.Link, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-4">Loại </label>
                        <div class="col-sm-8">
                            @Html.TextBoxFor(m => m.Type, new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.Type, "", new { @class = "text-danger" })
                        </div>
                    </div>

                </div>
            </div>
            <div class="modal-footer center">
                <button type="submit" class="btn btn-primary">Hoàn thành</button>

                <button type="button" class="btn btn-default" data-dismiss="modal">Đóng</button>
            </div>
        </div>
    }
</div>

<script>




</script>
@Scripts.Render("~/bundles/jqueryval")

Hinet.Web/Areas/NotificationArea/Views/Notification/_EditPartial.cshtml
@using Nami.Model.IdentityEntities
@using Nami.Model.IdentityEntities
@using Nami.Web.Areas.NotificationArea.Models

@model EditVM
@{ 

}
<div class="modal-dialog">
    @using (Ajax.BeginForm("Edit", "Notification", new { @area = "NotificationArea" }, new AjaxOptions()
    {
        HttpMethod = "POST",
        OnFailure = "AjaxFormError",
        OnSuccess = "AjaxFormSuccess",
    }, new { id = "editNotificationForm" }))
    {
        @Html.AntiForgeryToken()
        //HtmlHelper.UnobtrusiveJavaScriptEnabled = false;
    <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <div class="center">
                    <h4 class="modal-title">Cập nhật Thông báo hệ thống</h4>
                </div>
            </div>
            <div class="modal-body">
                <div class="form-horizontal">
 			@Html.HiddenFor(x=>x.Id)
				<div class="form-group">
				<label class="control-label col-sm-4">Đã đọc <span class="red">*</span></label>
				<div class="col-sm-8">
				@Html.TextBoxFor(m => m.IsRead, new { @class = "form-control" })
				@Html.ValidationMessageFor(m => m.IsRead, "", new { @class = "text-danger" })
				</div>
				</div>
				<div class="form-group">
				<label class="control-label col-sm-4">Người gửi </label>
				<div class="col-sm-8">
				@Html.TextBoxFor(m => m.FromUser, new { @class = "form-control" })
				@Html.ValidationMessageFor(m => m.FromUser, "", new { @class = "text-danger" })
				</div>
				</div>
				<div class="form-group">
				<label class="control-label col-sm-4">Người nhận </label>
				<div class="col-sm-8">
				@Html.TextBoxFor(m => m.ToUser, new { @class = "form-control" })
				@Html.ValidationMessageFor(m => m.ToUser, "", new { @class = "text-danger" })
				</div>
				</div>
				<div class="form-group">
				<label class="control-label col-sm-4">Nội dung <span class="red">*</span></label>
				<div class="col-sm-8">
				@Html.TextBoxFor(m => m.Message, new { @class = "form-control" })
				@Html.ValidationMessageFor(m => m.Message, "", new { @class = "text-danger" })
				</div>
				</div>
				<div class="form-group">
				<label class="control-label col-sm-4">Liên kết </label>
				<div class="col-sm-8">
				@Html.TextBoxFor(m => m.Link, new { @class = "form-control" })
				@Html.ValidationMessageFor(m => m.Link, "", new { @class = "text-danger" })
				</div>
				</div>
				<div class="form-group">
				<label class="control-label col-sm-4">Loại </label>
				<div class="col-sm-8">
				@Html.TextBoxFor(m => m.Type, new { @class = "form-control" })
				@Html.ValidationMessageFor(m => m.Type, "", new { @class = "text-danger" })
				</div>
				</div>

 

                </div>
            </div>
            <div class="modal-footer center">
                <button type="submit" class="btn btn-primary">Hoàn thành</button>

                <button type="button" class="btn btn-default" data-dismiss="modal">Đóng</button>
            </div>
        </div>
    }
</div>
<script>

</script>
@Scripts.Render("~/bundles/jqueryval")

Hinet.Web/Areas/NotificationArea/Views/Notification/_SearchPartial.cshtml
<div id="collapseDiv" class="panel-collapse collapse" aria-expanded="false" role="tabpanel">
    <div class="well SearchBox">

        @using (Ajax.BeginForm("searchData", "Notification", new { Area = "NotificationArea" },
            new AjaxOptions()
            {
                HttpMethod = "POST",
                OnFailure = "AjaxFormError",
                OnSuccess = "AjaxSearchSuccess",
            }, new { }))
        {
            @Html.AntiForgeryToken()
        <div class="row row-block">
		<div class="col-md-6 row-block">
			<div class="col-md-4 txt-label">Đã đọc</div>
			<div class="col-md-8">
				<input class="form-control width100" type="text" name="IsReadFilter" />
			</div>
		</div>

		<div class="col-md-6 row-block">
			<div class="col-md-4 txt-label">Người gửi</div>
			<div class="col-md-8">
				<input class="form-control width100" type="text" name="FromUserFilter" />
			</div>
		</div>

		<div class="col-md-6 row-block">
			<div class="col-md-4 txt-label">Người nhận</div>
			<div class="col-md-8">
				<input class="form-control width100" type="text" name="ToUserFilter" />
			</div>
		</div>

		<div class="col-md-6 row-block">
			<div class="col-md-4 txt-label">Nội dung</div>
			<div class="col-md-8">
				<input class="form-control width100" type="text" name="MessageFilter" />
			</div>
		</div>

		<div class="col-md-6 row-block">
			<div class="col-md-4 txt-label">Loại</div>
			<div class="col-md-8">
				<input class="form-control width100" type="text" name="TypeFilter" />
			</div>
		</div>


            <div class="col-md-12 center" style=" margin-top:20px;">
                <button id="btnSearch" type="submit" class="btn btn-labeled btn-primary btn-sm">
                    <span class="btn-label">
                        <i class="glyphicon glyphicon-search"></i>
                    </span>
                    Tìm kiếm
                </button>

                <a aria-expanded="false" href="#collapseDiv" data-toggle="collapse" role="button" class="btn btn-labeled btn-danger btn-sm">
                    <span class="btn-label"><i class="glyphicon glyphicon-remove"></i></span>
                    Đóng
                </a>
            </div>
        </div>

        }
    </div>
</div>